// src/utils/nutritionMappings.ts

export function mapNutrientNameToDbField(nutrientName: string): string | null {
  const mapping: Record<string, string> = {
    'Energy(a)': 'energy_with_fibre_kj',
    'Energy(b)': 'energy_without_fibre_kj',
    'Moisture(b)': 'moisture_g',
    'Protein': 'protein_g',
    'Total fat': 'total_fat_g',
    'Carbohydrate(c)': 'carbohydrate_g',
    'Starch': 'starch_g',
    'Total sugars': 'total_sugars_g',
    'Added sugars': 'added_sugars_g',
    'Free sugars': 'free_sugars_g',
    'Dietary Fibre': 'dietary_fibre_g',
    'Alcohol(d)': 'alcohol_g',
    'Ash': 'ash_g',
    'Vitamin A retinol equivalent': 'vitamin_a_retinol_ug',
    'Beta-carotene': 'beta_carotene_ug',
    'Pro Vitamin A': 'vitamin_a_re_ug',
    'Vitamin A RE': 'vitamin_a_re_ug',
    'Thiamin': 'thiamin_b1_mg',
    'Riboflavin': 'riboflavin_b2_mg',
    'Niacin': 'niacin_b3_mg',
    'Niacin equivalent': 'niacin_equivalents_mg',
    'Folate, natural': 'folate_natural_ug',
    'Folic acid': 'folic_acid_ug',
    'Total Folates': 'total_folates_ug',
    'Folate equivalent': 'dietary_folate_equivalents_ug',
    'Vitamin B6': 'vitamin_b6_mg',
    'Vitamin B12': 'vitamin_b12_ug',
    'Vitamin C': 'vitamin_c_mg',
    'Vitamin E': 'vitamin_e_mg',
    'Calcium': 'calcium_mg',
    'Iodine': 'iodine_ug',
    'Iron': 'iron_mg',
    'Magnesium': 'magnesium_mg',
    'Phosphorus': 'phosphorus_mg',
    'Potassium': 'potassium_mg',
    'Selenium': 'selenium_ug',
    'Sodium(e)': 'sodium_mg',
    'Zinc': 'zinc_mg',
    'Caffeine': 'caffeine_mg',
    'Cholesterol': 'cholesterol_mg',
    'Tryptophan': 'tryptophan_mg',
    'Saturated fat': 'saturated_fat_g',
    'Monounsaturated fat': 'monounsaturated_fat_g',
    'Polyunsaturated fat(c)': 'polyunsaturated_fat_g',
    'Linoleic acid': 'linoleic_acid_g',
    'Alpha-Linolenic acid': 'alpha_linolenic_acid_g',
    'EPA': 'epa_c20_5w3_mg',
    'DPA': 'dpa_c22_5w3_mg',
    'DHA': 'dha_c22_6w3_mg',
    'Total long chain omega 3 fatty acids': 'omega3_long_chain_total_mg',
    'Trans fatty acids': 'trans_fatty_acids_mg',
    'Vitamin A retinol equivalent': 'vitamin_a_retinol_ug',
    'Alpha-Linolenic acid': 'alpha_linolenic_acid_g',
    'Linoleic acid': 'linoleic_acid_g',
    'Niacin (B3)': 'niacin_b3_mg',
    'Riboflavin (B2)': 'riboflavin_b2_mg',
    'Thiamin (B1)': 'thiamin_b1_mg',
    'Preformed Vitamin A': 'vitamin_a_retinol_ug',
    'Total Fat(c)': 'total_fat_g'
  };
  return mapping[nutrientName] || null;
}

