name: Frontend CI/CD Deploy

on:
  push:
    branches:
      - main
  # Removed pull_request trigger to prevent deployment on PRs

jobs:
  build-and-deploy:
    # Only deploy on direct pushes to main branch (after PR merge)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'FIT5120-TA02/NutriPeek-frontend'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload to EC2 via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: ".next,public,package.json,next.config.js"
          target: "~/main-project-frontend"

      - name: Restart PM2 on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/main-project-frontend
            npm install --omit=dev
            pm2 restart frontend || pm2 start "npm start" --name frontend
